make_timelapse: Introduce compressed archiving.

diff --git a/bomthegov b/bomthegov
--- a/bomthegov
+++ b/bomthegov
@@ -1216,7 +1216,7 @@ make_timelapse() {
   # utc is also useful as bom/generic weather seems to prefer that for consistency (although, bom not always)
   timelapse_from="$(date --utc '+%Y-%m-%d_%H%M' --reference "${first_file}")"
   timelapse_to="$(date --utc '+%Y-%m-%d_%H%M' --reference "${last_file}")"
-  timelapse_file="${working_directory}/timelapse/[${id}] ${timelapse_from} to ${timelapse_to}.mp4"
+  timelapse_label="[${id}] ${timelapse_from} to ${timelapse_to}"
 
   # ensure directory to store created timelapse exists
   mkdir --parents "${working_directory}/timelapse" || exit 2
@@ -1230,7 +1230,7 @@ make_timelapse() {
       # capture the exit code of `ffmpeg` into the prepared array for success checking later
       # `-vf` to add padding to avoid potential "height not divisible by 2" crashes
       # *** ! *** `ffmpeg` requires everything on one long line here, as some versions break when using backslashes between switches for some reason *** ! ***
-      ffmpeg -r 25 -pattern_type glob -i "${scratch}/*.jpg" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" "${timelapse_file}"; ffmpeg_result+=(${?})
+      ffmpeg -r 25 -pattern_type glob -i "${scratch}/*.jpg" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" "${working_directory}/timelapse/${timelapse_label}.mp4"; ffmpeg_result+=(${?})
 
     # if we're making a timelapse of a radar, we use the assembled png files
     elif [[ "${context}" == 'radar' ]]; then
@@ -1238,30 +1238,40 @@ make_timelapse() {
       # `-vf` to add padding to avoid potential "height not divisible by 2" crashes
       # generate timestamp based on first and last collected frames
       # *** ! *** `ffmpeg` requires everything on one long line here, as some versions break when using backslashes between switches for some reason *** ! ***
-      ffmpeg -r 10 -pattern_type glob -i "${scratch}/*.png" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" "${timelapse_file}"; ffmpeg_result+=(${?})
+      ffmpeg -r 10 -pattern_type glob -i "${scratch}/*.png" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" "${working_directory}/timelapse/${timelapse_label}.mp4"; ffmpeg_result+=(${?})
     fi
 
   # test if all `ffmpeg` iterations were successful
     # use a subshell and set bash's Internal Field Separator to wordsplit the exit codes in ffmpeg_result with a plus sign instead of whitespace
     # then, parse the expanded array into `bc` with here-string, so the expanded array becomes 'var1+var2+var3' and so on, that `bc` can then sum ;)
     ffmpeg_success="$(IFS='+'; bc <<< "${ffmpeg_result[*]}")"
-  if [[ "${ffmpeg_success}" -eq 0 ]]; then
-    # after a successful timelapse is made, move the stored images folder to .archive and clean up the remaining folder once that's done
-    # clean up is needed so an empty ID doesn't appear in the available timelapse listings once a successful timelapse has been made from its data
-    printf '\n%s\n\n' "Timelapse video for ${id} ${context} successfully created."
+    if [[ "${ffmpeg_success}" -ne 0 ]]; then
+      printf '\n\n%s\n\n' "Error(s) occurred while attempting to assemble timelapse video for ${id} ${context}. Stopping."
+      exit 1
+    fi
+    printf '\n%s%s%s\n\n' "$(tput setaf 10)" "Timelapse video for ${id} ${context} successfully created." "$(tput sgr0)"
+
+  # after a successful timelapse is made, compress the stored images folder to .archive and clean up the remaining folder once that's done
+  # clean up is needed so an empty ID doesn't appear in the available timelapse listings once a successful timelapse has been made from its data
+    # delete the scratch area to save disk space
+    printf '%s ' "Cleaning up scrach disk..."
+    handle_spinner rm --recursive --force "${scratch:?}/" && printf '%s\n' "done."
+    # ensure archive directory exists
     mkdir --parents "${working_directory}/images/.archive/${context}" || exit 2
-    cd "${working_directory}" || exit 2
-    mv --force "${working_directory}/images/${context}/${id}" "${working_directory}/images/.archive/${context}"
-  else
-    printf '\n\n%s\n\n' "Error(s) occurred while attempting to assemble timelapse video for ${id} ${context}. Stopping."
-    exit 1
-  fi
+    # compress the collected image set into the archive
+    # enter the image storage directory first
+    cd "${working_directory}/images/${context}/" || exit 2
+    printf '%s ' "Archiving original images..."
+    if handle_spinner tar --create --gzip --label="${id}" --file="${working_directory}/images/.archive/${context}/${timelapse_label}.tar.gz" "${id}/"; then
+      # remove originals now they're successfully archived
+      handle_spinner rm --recursive --force "${working_directory}/images/${context}/${id}/" && printf '%s\n' "done."
+    fi
 
   # encountered no error exit, so stop timer and report how long we've been running
   timer_stop=$(date +%s)
-  printf '%s\n\n' "Total processing time was $(display_pretty_timer $((timer_stop-timer_start)))."
+  printf '\n%s\n\n' "Total processing time was $(display_pretty_timer $((timer_stop-timer_start)))."
   # open the timelapse video file in the user's preferred application
-  ##xdg-open "${timelapse_file}"
+  ##xdg-open "${working_directory}/timelapse/${timelapse_label}.mp4"
 }
 
 
