make_timelapse: Add spinner for convert. Add flatten_images.

diff --git a/bomthegov b/bomthegov
--- a/bomthegov
+++ b/bomthegov
@@ -1104,6 +1104,102 @@ download_radar_images() {
   printf '%s\n\n' "Total fetching time was $(display_pretty_timer $((timer_stop-timer_start)))."
 }
 
+flatten_images() {
+  # called from inside make_timelapse to display spinner against
+  # prepare each image as video frames
+  # if we're making a timelapse of satellite images, ensure we flatten each image to a jpeg, as tifs have multiple layers which `ffmpeg` doesn't like
+  if [[ "${context}" == 'satellite' ]]; then
+    # *** imagemagick defaults need to be tweaked from now on for dealing with the large canvas sizes of himawari satellite images ***
+    # largest known satellite image sets are IDE0409 with 0.5km per pixel resolution: results in image sizes of 24444 x 16667 @ 96dpi, which is ~408 megapixels
+    # default megapixel limit for imagemagick is 128MP, and so conversion crashes with defaults when dealing with IDE0409 (thanks for the bug report @matt_brown!)
+    # set MAGICK_CONFIGURE_PATH to import bundled policy.xml settings to from .config folder to explicitly increase width and height limits, etc
+    # documentation at: https://imagemagick.org/script/resources.php
+
+    # now actually do the conversion
+    for file in "${files[@]}"; do
+      printf '\r%s %d%s ' "Flattening satellite images..." $((count * 100 / ${#files[@]})) '%'
+      # get the name of the current file only by stripping off its path
+      current_filename="${file##*/}"
+      # tif files from bom have multiple layers, and if just using filenames, imagemagick splits those layers into multiple files which is unwanted
+      # so use [0] after file name which `convert` interprets as "get the first layer only"
+      # ensure we are converting to jpegs by removing current filename's extension and substituting .jpg using parameter expansion
+      # also do `convert` quietly to avoid any warning messages that we might encounter about tif layers that are now irrelevant
+      # capture the exit code of `convert` into its prepared array for success checking later
+      # scale to requested resolution only if image is larger, i.e. `>` (which needs to be escaped from the shell with a backslash)
+      convert -quiet -scale "${resolution}"\> "${file}[0]" "${scratch}/${current_filename%.*}.jpg"; convert_result+=(${?})
+        # himawari satellite images have no timestamps on them, so if handling their IDs here, append that information to current frame
+        # IDs that are currently known are in the range IDE004xx, i.e. 401 to 437 so if we get a match on that, add our own timestamp label
+        # use the served file metadata parsed through `date` to make our timestamp
+        # the text passed to `convert` to be created, is in the 'label' argument
+        if [[ "${id}" =~ ^IDE004[0-3][0-9]$ ]]; then
+          convert "${scratch}/${current_filename%.*}.jpg" \
+            -background black -fill white -font Ubuntu-Mono -pointsize 18 label:"${this_name} - $(date --utc --reference "${current_filename}")" \
+            -gravity center -append "${scratch}/${current_filename%.*}.jpg"; convert_result+=(${?})
+        fi
+      # advance the progress meter
+      ((count++))
+    done
+
+  # if we're making a timelapse of a radar, assemble its layers
+  elif [[ "${context}" == 'radar' ]]; then
+    # order of layers: legend -> geographical background -> topography -> location names -> radar data range circle -> current rain radar data
+    # determine what legend is required first, based on it's ID structure
+      # if ID ends in a number, it's a rainfields data; use legend 0 (rain rate scale, light -> heavy)
+      [[ "${id}" =~ [0-9]$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.0.png"
+      # if ID ends in A B C or D then it's a rainfields data; use legend 1 (rainfall in mm)
+      [[ "${id}" =~ [A-D]$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.1.png"
+      # if ID ends in I it's doppler wind data; use legend 2 (colour codes for towards/away from radar)
+      [[ "${id}" =~ I$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.2.png"
+
+    # check layers and legend files are available as we expect before further processing
+    if [[ ! -s "${legend}" || $(find layers -type f -not -empty -print | wc --lines) -eq 0 ]]; then
+      printf '%s\n' "The ${id} ${context} has collected images ready to timelapse, but is missing its legend or layer files."
+      printf '%s\n\n' "A timelapse cannot be created without these layers."
+      printf '%s\n\n' "Are you sure fecthing images for ${id} completed successfully?"
+      exit 1
+    fi
+
+    # if the current radar ID is the national radar, it does not have topography, locations, or range layers so don't process them (eyeroll)
+    # otherwise, it's a radar as "usual" so assemble those layers
+    # such a messy bom
+    if [[ "${id}" == 'IDR00004' ]]; then
+      # the conversion loop should exclude layers that don't exist for national radar
+      for file in "${files[@]}"; do
+        printf '\r%s %d%s ' "Flattening radar image layers..." $((count * 100 / ${#files[@]})) '%'
+        # do conversion quietly
+        convert -quiet \
+          "${legend}" \
+          "layers/*.background.png" \
+          "${file}" -flatten "${scratch}/${file##*/}"; convert_result+=(${?})
+        # advance the progress meter
+        ((count++))
+      done
+    else
+      # a radar as usual, so conversion loop should assemble known/desired layers
+      for file in "${files[@]}"; do
+        printf '\r%s %d%s ' "Flattening radar image layers..." $((count * 100 / ${#files[@]})) '%'
+        convert -quiet \
+          "${legend}" \
+          "layers/*.background.png" \
+          "layers/*.topography.png" \
+          "layers/*.locations.png" \
+          "layers/*.range.png" \
+          "${file}" -flatten "${scratch}/${file##*/}"; convert_result+=(${?})
+        ((count++))
+      done
+    fi
+  fi
+
+# if conversion encountered any errors, stop here
+  # arrays implicitly concatenate inside [[ ]] so use explicit * for expanding the array instead of @
+  # `convert` only returns two exit codes: '0' for success as normal, or '1' for any failure
+  # so, only need to check for the existence of '1' anywhere
+  if [[ "${convert_result[*]}" =~ 1 ]]; then
+    printf '\n\n%s\n%s\n\n' "Error(s) occurred during image preparation." "Creating timelapse failed. Stopping."
+    exit 1
+  fi
+}
+
 make_timelapse() {
   # this function handles the pre and post processing for making timelapse images out of an $id that is set inside handle_timelapse_images
   # this function is expected to be called inside handle_timelapse_images after init has been run to set up temporary storage, etc
@@ -1146,115 +1242,7 @@ make_timelapse() {
   # set stopwatch to keep track of total run time for assembling timelapse, starting from now
   timer_start=$(date +%s)
 
-  # prepare each image as video frames
-    # if we're making a timelapse of satellite images, ensure we flatten each image to a jpeg, as tifs have multiple layers which `ffmpeg` doesn't like
-    if [[ "${context}" == 'satellite' ]]; then
-      # *** imagemagick defaults need to be tweaked from now on for dealing with the large canvas sizes of himawari satellite images ***
-      # largest known satellite image sets are IDE0409 with 0.5km per pixel resolution: results in image sizes of 24444 x 16667 @ 96dpi, which is ~408 megapixels
-      # default megapixel limit for imagemagick is 128MP, and so conversion crashes with defaults when dealing with IDE0409 (thanks for the bug report @matt_brown!)
-      # set MAGICK_CONFIGURE_PATH to import bundled policy.xml settings to from .config folder to explicitly increase width and height limits, etc
-      # documentation at: https://imagemagick.org/script/resources.php
-
-      # now actually do the conversion
-      # hide the cursor while displaying progress, as on some systems it "jumps everywhere" during the loop
-      tput civis
-      for file in "${files[@]}"; do
-        printf '%s %d%s ' "Flattening satellite images..." $((count * 100 / ${#files[@]})) '%'
-        # get the name of the current file only by stripping off its path
-        current_filename="${file##*/}"
-        # tif files from bom have multiple layers, and if just using filenames, imagemagick splits those layers into multiple files which is unwanted
-        # so use [0] after file name which `convert` interprets as "get the first layer only"
-        # ensure we are converting to jpegs by removing current filename's extension and substituting .jpg using parameter expansion
-        # also do `convert` quietly to avoid any warning messages that we might encounter about tif layers that are now irrelevant
-        # capture the exit code of `convert` into its prepared array for success checking later
-        # scale to requested resolution only if image is larger, i.e. `>` (which needs to be escaped from the shell with a backslash)
-        convert -quiet -scale "${resolution}"\> "${file}[0]" "${scratch}/${current_filename%.*}.jpg"; convert_result+=(${?})
-          # himawari satellite images have no timestamps on them, so if handling their IDs here, append that information to current frame
-          # IDs that are currently known are in the range IDE004xx, i.e. 401 to 437 so if we get a match on that, add our own timestamp label
-          # use the served file metadata parsed through `date` to make our timestamp
-          # the text passed to `convert` to be created, is in the 'label' argument
-          if [[ "${id}" =~ ^IDE004[0-3][0-9]$ ]]; then
-            convert "${scratch}/${current_filename%.*}.jpg" \
-              -background black -fill white -font Ubuntu-Mono -pointsize 18 label:"${this_name} - $(date --utc --reference "${current_filename}")" \
-              -gravity center -append "${scratch}/${current_filename%.*}.jpg"; convert_result+=(${?})
-          fi
-        # advance the progress meter
-        ((count++))
-        # return cursor to the start of the line
-        printf '\r'
-      done
-      # restore the cursor
-      tput cnorm
-
-    # if we're making a timelapse of a radar, assemble its layers
-    elif [[ "${context}" == 'radar' ]]; then
-      # order of layers: legend -> geographical background -> topography -> location names -> radar data range circle -> current rain radar data
-      # determine what legend is required first, based on it's ID structure
-        # if ID ends in a number, it's a rainfields data; use legend 0 (rain rate scale, light -> heavy)
-        [[ "${id}" =~ [0-9]$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.0.png"
-        # if ID ends in A B C or D then it's a rainfields data; use legend 1 (rainfall in mm)
-        [[ "${id}" =~ [A-D]$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.1.png"
-        # if ID ends in I it's doppler wind data; use legend 2 (colour codes for towards/away from radar)
-        [[ "${id}" =~ I$ ]] && legend="${working_directory}/images/radar/legend/IDR.legend.2.png"
-
-      # check layers and legend files are available as we expect before further processing
-      if [[ ! -s "${legend}" || $(find layers -type f -not -empty -print | wc --lines) -eq 0 ]]; then
-        printf '%s\n' "The ${id} ${context} has collected images ready to timelapse, but is missing its legend or layer files."
-        printf '%s\n\n' "A timelapse cannot be created without these layers."
-        printf '%s\n\n' "Are you sure fecthing images for ${id} completed successfully?"
-        exit 1
-      fi
-
-      # if the current radar ID is the national radar, it does not have topography, locations, or range layers so don't process them (eyeroll)
-      # otherwise, it's a radar as "usual" so assemble those layers
-      # such a messy bom
-      if [[ "${id}" == 'IDR00004' ]]; then
-        # the conversion loop should exclude layers that don't exist for national radar
-        # hide the cursor while displaying progress, as on some systems it "jumps everywehere" during the loop
-        tput civis
-        for file in "${files[@]}"; do
-          printf '%s %d%s ' "Flattening radar image layers..." $((count * 100 / ${#files[@]})) '%'
-          # do conversion quietly
-          convert -quiet \
-            "${legend}" \
-            "layers/*.background.png" \
-            "${file}" -flatten "${scratch}/${file##*/}"; convert_result+=(${?})
-          # advance the progress meter
-          ((count++))
-          # return cursor to the start of the line
-          printf '\r'
-        done
-        # restore the cursor
-        tput cnorm
-      else
-        # hide the cursor while displaying progress, as on some systems it "jumps everywehere" during the loop
-        tput civis
-        # a radar as usual, so conversion loop should assemble known/desired layers
-        for file in "${files[@]}"; do
-          printf '%s %d%s ' "Flattening radar image layers..." $((count * 100 / ${#files[@]})) '%'
-          convert -quiet \
-            "${legend}" \
-            "layers/*.background.png" \
-            "layers/*.topography.png" \
-            "layers/*.locations.png" \
-            "layers/*.range.png" \
-            "${file}" -flatten "${scratch}/${file##*/}"; convert_result+=(${?})
-          ((count++))
-          printf '\r'
-        done
-        # restore the cursor
-        tput cnorm
-      fi
-    fi
-
-  # if conversion encountered any errors, stop here
-    # arrays implicitly concatenate inside [[ ]] so use explicit * for expanding the array instead of @
-    # `convert` only returns two exit codes: '0' for success as normal, or '1' for any failure
-    # so, only need to check for the existence of '1' anywhere
-    if [[ "${convert_result[*]}" =~ 1 ]]; then
-      printf '\n\n%s\n%s\n\n' "Error(s) occurred during image preparation." "Creating timelapse failed. Stopping."
-      exit 1
-    fi
+  handle_spinner flatten_images
 
   # everything fine, so now get the first and last names of files we're timelapsing, for use in a moment to generate label for mp4 file
   first_file="${files[0]##*/}"
